### ISSUE TITLE
previously unstated dependency on surveillance creates warning

### ISSUE THREAD

**Issue by thibautjombart** [Hackout2/incidence#2]
The code generating "hagelloch.obk.R" has an unstated dependency with surveillance which was breaking the package at d851b54fea2a2d.

Temporary fix adds the dependency (added un-needed @import to getIncidence.R), but now we get the following warning:

```
* checking whether package ‘incidence’ can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import by ‘surveillance::year’ when loading ‘incidence’
```

_Suggested course of action:_ remove the .R file generating the data (I don't think people will check it) put the dataset as .RData in /data, and remove the un-needed dependency on surveillance, unless it is actually needed somewhere else.

**Comment by mhoehle** [comment]
I never really got the hang on the namespacing - thought that including surveillance in suggests would be enough. I followed the suggested course of action moving the old haggeloch.obk.R into a new directory develop/ and replacing it with data/hagelloch.obk.RData. The develop directory was added to .Rbuildignore and the un-needed @import removed. 

While at it, I took the opportunity to merge with branch 'noshiny' such that the .Rd file now links to the wiki. The package now compiles with 2 notes on my system - looking forward to the travis check.

**Comment by thibautjombart** [comment]
Awesome ! I'm at an Ebola workshop all day but will check soon. Green light
is back on Travis :)
Cheers
Thibaut

**Comment by karthik** [comment]
> I never really got the hang on the namespacing

Namepsaces aren't that hard. If you need functions from other packages, do two things.
a) Add it to Imports under the description. This assumes that the package is available on CRAN or Bioconductor.
b) Import either the package, assuming you need a large majority of the functions, using:

``` r
#' @import dplyr
```

or just a small set of functions:

``` r
#' @importFrom dplyr rbind_all rbind_list
```

Then next time you run `document()`, `devtools` will add the right imports to the `NAMESPACE` file. 

I see this error:

```
Namespace in Imports field not imported from: ‘surveillance’
  All declared Imports should be used.
```

suggesting that nothing from that Import is being directly called in any function.

**Comment by thibautjombart** [comment]
Thanks a lot for the detailed reply.
In this case I think surveillance was used in some R code in /data, which
was used to generate a RData. As we replaced the R code by a RData, I think
we no longer need this dependency.
Cheers
Thibaut
